#!/usr/bin/env bash
# is a factors challenge

check_factor()
{
	if [ $# -ne 3 ];
        then
                args=("$@")
                count=0
                num4=1
                for a in ${args[*]};
                do
                        if [ $count -gt 1 ];
                        then
                                num4=$(echo $a*$num4 | bc)
                        fi
                        count=$((count + 1))
                done
        else
                num4=$3
        fi

        num3=$2
        num0=$(echo "$1" | tr ':' '=')

        result=$(echo "if($num4 > $num3) 1 else 0" | bc)
	        if ((result == 1)); then
		        numcp=$num3
		        num3=$num4
		        num4=$numcp
                fi

        echo "$num0$num3*$num4"
}

if [ $# -ne 1 ]
then
        echo 'Usage: factors <file>'
        exit 1
else

        while read l
        do

                result=$(factor "$l")
                check_factor $result

        done < "$1"
fi

