#!/usr/bin/env bash
# is a factors challenge

checker_factor()
{
	if [ $# -ne 3 ];
        then
                arggs=("$@")
                counnt=0
                num4=1
                for k in ${arggs[*]};
                do
                        if [ $counnt -gt 1 ];
                        then
                                num4=$(echo $a*$num4 | bc)
                        fi
                        counnt=$((counnt + 1))
                done
        else
                num4=$3
        fi

        num3=$2
        nums=$(echo "$1" | tr ':' '=')

        res=$(echo "if($num4 > $num3) 1 else 0" | bc)
	        if ((res == 1)); then
		        numcp=$num3
		        num3=$num4
		        num4=$numcp
                fi

        echo "$nums$num3*$num4"
}

if [ $# -ne 1 ]
then
        echo 'Usage: factors <file>'
        exit 1
else

        while read i
        do

                res=$(factor "$i")
                checker_factor $res

        done < "$1"
fi

